### ISSUE TITLE
problem about Blender

### ISSUE THREAD

**Issue by tp030ny** [EdwardSmith1884/3D-IWGAN#1]
I got some problem of implementation of the code 'DataSetPrep.py'. The Render-process can't work on my computer, and the error information as follows: 

'Error: File written by newer Blender binary (270.5), expect loss of data!
Traceback (most recent call last):
  File "/home/yves/project_gan/3D_gan/ours/render_pipeline/render_model_views.py", line 23, in <module>
    bpy.context.user_preferences.addons['cycles'].preferences.compute_device_type = 'CUDA'
AttributeError: 'NoneType' object has no attribute 'compute_device_type''

Which version of the Blender utilized in this work? and which of the python version? 
I set the blender path as ''g_blender_executable_path = '/home/yves/blender-2.70-linux-glibc211-x86_64/blender' #!! MODIFY if necessary'', is it right?

**Comment by EdwardSmith1884** [comment]
I pushed a fix just now, lines 23 and 24 in render_model_views.py were causing problems
