### ISSUE TITLE
How to compute AP(Average Precision) for test evaluation over IKEA Dataset?

### ISSUE THREAD

**Issue by li-zemin** [EdwardSmith1884/3D-IWGAN#10]
Hello, in your paper 3D-VAE-IWGAN, you tested your model over IKEA Dataset and scored with Avarage Precision for comparing to 3D-VAE-GAN. I know that the evaluation critic is introduced from [Girdhar](https://arxiv.org/abs/1603.08637) , however i am not finding the clear definition. So could tell me the definition of Average Precision? Thank you!

**Comment by EdwardSmith1884** [comment]
The function I used to compute it is [here]( http://scikit-learn.org/stable/modules/generated/sklearn.metrics.average_precision_score.html), the definition is included in the page.

**Comment by li-zemin** [comment]
Thank you very much!
