### ISSUE TITLE
could you help with me ,when i download your data using Datasetpre.py.error like this 

### ISSUE THREAD

**Issue by AmyWan** [EdwardSmith1884/3D-IWGAN#11]
downloading
------------
rendering
------------
2018-07-05 22:18:20.745281
Image set number: 0
0it [00:00, ?it/s]
2018-07-05 22:18:20.867954
Image set number: 1
0it [00:00, ?it/s]

**Comment by EdwardSmith1884** [comment]
Do you have blender and Matlab installed? Also did give the binvox executable permissions? If not there will be some error that is thrown.  Also there is a setting on line 41 of this file
```python 
debug_mode = 1
```
You can set this to 0 to see the error being thrown. If you can't figure it out, please post the error in here for me to see. Just as a quick point, I have another repo [here](https://github.com/EdwardSmith1884/Multi-View-Silhouette-and-Depth-Decomposition-for-High-Resolution-3D-Object-Representation) which is all about 3D reconstruction. The data-set creation tool and the reconstruction code is all a lot more optimised, even for the simple low resolution reconstruction algorithm. If your only goal is reconstruction then this is a much easier place to start.

**Comment by AmyWan** [comment]
I have the big problem,please help.I only dowload the .obj,and other files is empty .I had installed all software,and set the debug_mode=0,why Happen this?

**Comment by EdwardSmith1884** [comment]
sorry I had it wrong, Keep debug_mode = 1 and show me the error code you see. Also If you are trying to do object reconstruction I recommend trying my other project instead which can be found [here](https://github.com/EdwardSmith1884/Multi-View-Silhouette-and-Depth-Decomposition-for-High-Resolution-3D-Object-Representation). The data preperation phase is quicker and far more optimised, and the results are far superior.

**Comment by AmyWan** [comment]
yes,I want to create a network ,a input image  to 3d model,but I have had many questions,
last time ,you showed me your other data preperation,I also couldnt download the data ,i had not install the matlab ,beacause your file is not rementioned.
