### ISSUE TITLE
About the average precision score

### ISSUE THREAD

**Issue by yuzhe233** [EdwardSmith1884/3D-IWGAN#15]
Thanks for your beautiful codes,I'm doing something about the 3d-iwgan recently.I wander to know how to work out the average precision socre,thanks!

**Comment by EdwardSmith1884** [comment]
The function I used to compute it is : https://scikit-learn.org/stable/modules/generated/sklearn.metrics.average_precision_score.html . Sorry for the wait.

**Comment by yuzhe233** [comment]
Thank you very much,there is another problem is that how to read the model into ram,I'm just beginner of this,hope you can tell something about it.

**Comment by EdwardSmith1884** [comment]
do you mean how do you visualize the models?

**Comment by yuzhe233** [comment]
I mean the network，I‘ve just put the trained network into the ram，but I’ve no idea about  how to input a new image and output a 3D object to test the  trained net.

**Comment by EdwardSmith1884** [comment]
Sorry, This is an older repo and things are a little more scattered. You can visualize using the script at https://github.com/EdwardSmith1884/3D-IWGAN/blob/master/scripts/visualize.py.  To use this just call python visualize.py VOXEL_FILE, where voxel_file is the file created during training and saved to savepoint/NAME/EPOCH.npy.

**Comment by yuzhe233** [comment]
Thanks for your explanation，I’ll try.
