### ISSUE TITLE
A quick question

### ISSUE THREAD

**Issue by weich97** [EdwardSmith1884/3D-IWGAN#16]
Hi Edward,

     I am a student who is attending an AI hackathon together with other students (I am just a beginner). I would like to use your code as our team code base, to accelerate the code and interact with AI at scale. We will surely cite your paper, but we need to get your permission to do so. Also, we are glad to receive other advices or warnings if you have. 

     Thank you very much!

Best Regards,

Weicheng

**Comment by EdwardSmith1884** [comment]
Of  course, feel free to use it. That's what it is there for.

**Comment by weich97** [comment]
Thank you very much!
