### ISSUE TITLE
Question about 3D-GAN

### ISSUE THREAD

**Issue by abelmouhcine** [EdwardSmith1884/3D-IWGAN#17]
Hello,

Is the 3D-GAN you implemented the same as the one described in the original paper and have you been able to generate the same results with it?

**Comment by EdwardSmith1884** [comment]
Yes to both. It was implemented before their code was released so there may be some differences from ambiguities in their paper and because I use a lower voxel resolution. I got the same results as described in their paper at this lower resolution.

**Comment by abelmouhcine** [comment]
Thanks for your quick response! 
In your implementation there is a fully connected layer, that I didn't find in the 3D-GAN paper. Anyway, I'm doing now some testing based on the architecture you proposed (without wasserstain), could you please tell me whether the default hyper-parameter values are the one that gave you good quality generations?

**Comment by EdwardSmith1884** [comment]
Yes I use fully connected layer to reshape the latent vector, but that is a fairly small change. Yes the default hyper parameters are the ones I used for the generations you can see on the repo.
