### ISSUE TITLE
im geting following error while running the code

### ISSUE THREAD

**Issue by LingaswamyD23** [EdwardSmith1884/3D-IWGAN#18]
Traceback (most recent call last):
  File "DataSetPrep.py", line 7, in <module>
    import scripts.binvox_rw
ImportError: bad magic number in 'scripts': b'\x03\xf3\r\n'

Traceback (most recent call last):
  File "/home/student/Desktop/3D-IWGAN-master/scripts/render_pipeline/render_model_views.py", line 30, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
Read blend: /home/student/Desktop/3D-IWGAN-master/scripts/render_pipeline/blank.blend

**Comment by EdwardSmith1884** [comment]
you need to install numpy in the version of python that blender is using

**Comment by Lingaswamy12345** [comment]
Traceback (most recent call last):
  File "DataSetPrep.py", line 298, in <module>
    overlay()
  File "DataSetPrep.py", line 258, in overlay
    matlab_cmd = "addpath('%s'); overlay_background('%s','%s','%s', '%s', %f, 1);" % (os.path.join(g_render4cnn_root_folder, 'render_pipeline'), img_dir,  overlay_dir, background_list, backgrounds, 1.0)
NameError: name 'g_render4cnn_root_folder' is not defined

**Comment by Lingaswamy12345** [comment]
> Traceback (most recent call last):
> File "DataSetPrep.py", line 298, in
> overlay()
> File "DataSetPrep.py", line 258, in overlay
> matlab_cmd = "addpath('%s'); overlay_background('%s','%s','%s', '%s', %f, 1);" % (os.path.join(g_render4cnn_root_folder, 'render_pipeline'), img_dir, overlay_dir, background_list, backgrounds, 1.0)
> NameError: name 'g_render4cnn_root_folder' is not defined

resolved by adding path

**Comment by Lingaswamy12345** [comment]
NameError: name 'g_render4cnn_root_folder' is not defined

overlaying is not executing......

**Comment by Lingaswamy12345** [comment]
> NameError: name 'g_render4cnn_root_folder' is not defined
> 
> overlaying is not executing......

please anyone help out with this

**Comment by Lingaswamy12345** [comment]
> Traceback (most recent call last):
> File "DataSetPrep.py", line 298, in
> overlay()
> File "DataSetPrep.py", line 258, in overlay
> matlab_cmd = "addpath('%s'); overlay_background('%s','%s','%s', '%s', %f, 1);" % (os.path.join(g_render4cnn_root_folder, 'render_pipeline'), img_dir, overlay_dir, background_list, backgrounds, 1.0)
> NameError: name 'g_render4cnn_root_folder' is not defined

resolved
