### ISSUE TITLE
"from path import Path" in convert_shapenet10.py 

### ISSUE THREAD

**Issue by brotherNanNan** [EdwardSmith1884/3D-IWGAN#2]
Hi:
  Great job! however, i encounter a mistake in convert_shapenet10.py, "path" can't be found.

**Comment by EdwardSmith1884** [comment]
Hi, 
From what I've read your path.py version may be outdated. I would suggest upgrading your path.py module:

sudo pip uninstall path.py
sudo pip install path.py

or just 
 
sudo pip install path.py --upgrade

let me know if that fixes the problem

**Comment by brotherNanNan** [comment]
@EdwardSmith1884 , what's the version of python and tensorflow that you used ? I  think  the problem may be the python3 i used

**Comment by EdwardSmith1884** [comment]
@brotherNanNan 
Ah yes, 
I used python2 when I wrote this. That is probably the issue. 
Just for your information the tensorflow version this code is written for is 1.2.1
