### ISSUE TITLE
about the module “Path”

### ISSUE THREAD

**Issue by TowerTowerLee** [EdwardSmith1884/3D-IWGAN#20]
When I was converting the dataset according to 3D-Reconstruction-Kinect/3D_generation.sh, I met the problem running this file: convert_shapenet10.py.
Here is the error message:

> Traceback (most recent call last):
>   File "convert_shapenet10.py", line 5, in <module>
>     from path import Path
> ModuleNotFoundError: No module named 'path'

Although I googled it many times, but I still don't know how to solve it, 'cause it seems that there is no such module called "path". Does it matter if not running this file? It seems important..

My version is python 3.6 by the way, with tensorflow 1.13.1 in Windows system

**Comment by mallorbc** [comment]
I had troubles with this as well.  Try ```pip install path.py```.  That should fix your issue.

**Comment by TowerTowerLee** [comment]
Thank you.I have already solved this issue.Hope to keep in contact with you if there are more problems.
