### ISSUE TITLE
windows environment seems cannot run binox

### ISSUE THREAD

**Issue by TowerTowerLee** [EdwardSmith1884/3D-IWGAN#21]
When running the function binvox(), DataSetPrep.py reports an error saying that some buffers can be used under Linux only. I copied the specific command just to solve the path problem, but now I'm not sure if it can still succeed under Window environment. 

**Here is the code I write:**

```
command = "binvox -d 100 -pb data/objects/chair/6db2255a51caf84e823e7e244bf84209.obj"
os.system('%s %s' % (command, ''))
```
**And here is part of the error report:**

> ......
> Read 6840 faces, 1774 vertices.
> Mesh memory use is 17888 KB (17 MB)
>   Mesh::normalize, bounding box: [-0.224797, -0.421669, -0.147179, 1] - [0.224797, 0.421669, 0.147179, 1]
>     longest length: 0.843338
>   normalization transform:
>   (1) translate [0.224797, 0.421669, 0.147179, 1], (2) scale 1.18576, (3) translate [0, 0, 0]
>   got mesh bounding box [-0.224797, -0.421669, -0.147179, 1] - [0.224797, 0.421669, 0.147179, 1]
> 
> voxel model dimension: 200
> Error: sorry, off-screen buffers can be used under Linux only

**Comment by mallorbc** [comment]
what happens when you try the command giving the complete path to the binvox binary? Such as ```C:\binvox_download\binvox -d 100 -pb data/objects/chair/6db2255a51caf84e823e7e244bf84209.obj```

**Comment by TowerTowerLee** [comment]
> what happens when you try the command giving the complete path to the binvox binary? Such as `C:\binvox_download\binvox -d 100 -pb data/objects/chair/6db2255a51caf84e823e7e244bf84209.obj`

I have tried to use this method like you said,but it still doesn't work and  problem is also that problem.

**Comment by TowerTowerLee** [comment]
I have tried to use this method like you said,but it still doesn't work and problem is also that problem.





------------------ 原始邮件 ------------------
发件人: "mallorbc"<notifications@github.com>;
发送时间: 2019年7月9日(星期二) 凌晨2:21
收件人: "EdwardSmith1884/3D-IWGAN"<3D-IWGAN@noreply.github.com>;
抄送: "信研1803班李亚琪"<815046276@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [EdwardSmith1884/3D-IWGAN] windows environment seems cannot runbinox (#21)




what happens when you try the command giving the complete path to the binvox binary? Such as C:\binvox_download\binvox -d 100 -pb data/objects/chair/6db2255a51caf84e823e7e244bf84209.obj

**Comment by TowerTowerLee** [comment]
> what happens when you try the command giving the complete path to the binvox binary? Such as `C:\binvox_download\binvox -d 100 -pb data/objects/chair/6db2255a51caf84e823e7e244bf84209.obj`

I just solved this issue by replace the command  'pb' by 'c' like this:
'F:/laboratory/3Dpaper/3D-IWGAN-master/3D-Reconstruction-Image/binvox -d 100 -c data/objects/chair/6db2255a51caf84e823e7e244bf84209.obj'
And the binvox file can be created.
Thank you again for checking my questions and answering them patiently.
