### ISSUE TITLE
about data's version

### ISSUE THREAD

**Issue by CRISZJ** [EdwardSmith1884/3D-IWGAN#24]
the normal expression of 3d voxel file is .binvox.do you konw how to convert the result of .npy to .binvox?

**Comment by EdwardSmith1884** [comment]
I realize this is a tad old but does this not solve your problem: https://github.com/EdwardSmith1884/3D-IWGAN/blob/3cb004619bd7e37d2b33cf300622154656051615/scripts/binvox_rw.py#L233
