### ISSUE TITLE
The problem of Reconstruction of 3D Objects from Single Perspective Depth Scans

### ISSUE THREAD

**Issue by caixialiu-bjut** [EdwardSmith1884/3D-IWGAN#26]
Hi, thank you for your code.  I have the problem about "Reconstruction of 3D Objects from Single Perspective Depth Scans".
1.In the 3D_generation.sh
    # # convert to our format
    python convert_shapenet10.py 3DShapeNets
    python Kinect_setup.py chair
The data produced by above codes are from ShapeNet . However, the data in the paper show ModelNet, such as ' Example synthetic single perspective kinetic scans created by the authors, produced from the chair class of the ModelNet10 dataset.' in fig8.  It's a contradiction.

2.I guess that  Kinect-VAE-3D-IWGAN.py aims at  fig8, and is it right? Could you share the code that converts Kinect RGB-D images (A Large Dataset of Object Scans dataset [33] ) to voxel representations(fig.10)  ? 

Thanks very much! Look forward to your reply.

**Comment by EdwardSmith1884** [comment]
Hi, 

1. Yes the names are confusing here, if you download the data you will see that it is in fact ModelNet. The citation for ModelNet is weirdly enough : "3D ShapeNets: A Deep Representation for Volumetric Shapes", the download is correct however.  

2. Unfortunately I lost track of this code. It was never in any way automated to the degree that it could be shared or ready for public release. 

Hope this helps, 

Ed
