### ISSUE TITLE
about Voxsize

### ISSUE THREAD

**Issue by brotherNanNan** [EdwardSmith1884/3D-IWGAN#3]
Hi,
      If i use 64 * 64 * 64 size volume as input and set output_size=64, wheather "discriminator" in the models.py should be adjusted or not ? thanks！

**Comment by EdwardSmith1884** [comment]
Hi,
sorry for the long time to reply, I simply did not see it until now. From what I remember you do not need to change anything for it to run and produce good results. It is possible that creating a larger network would benefit the training as my architecture was optimised for a lower resolution. I'm sure this is old new, so let me know if you have any more questions, I'm sorry again this took so long.

**Comment by brotherNanNan** [comment]
@EdwardSmith1884  thanks for your reply~
