### ISSUE TITLE
About "models.py"

### ISSUE THREAD

**Issue by li-zemin** [EdwardSmith1884/3D-IWGAN#5]
HI,
I was learning your code, thanks for your contributions.
The problem is that, "net_h3" and "MBD" was not found in "models.py", can you help me fix this bug, maybe it was my negligence.
Thank you!

**Comment by EdwardSmith1884** [comment]
Hi, 
So 'net_h3' was only available with the VAE_Loss parameter in the discriminator, which is never called in the project. MBD was an option for  minibatch discrimination which in the end I did not include in the project, I just forgot to remove it. They are both code I meant to remove during refactoring but forgot to, they are now removed, Thank you for letting me know.
