### ISSUE TITLE
AttributeError: 'module' object has no attribute 'ops'

### ISSUE THREAD

**Issue by majikbyte** [EdwardSmith1884/3D-IWGAN#6]
thanks for your code. 

FYI

tl.ops.set_gpu_fraction(sess=sess, gpu_fraction=0.998)
AttributeError: 'module' object has no attribute 'ops'

Apparently ops was replaced with util and the first argument is no longer necessary.

**Comment by li-zemin** [comment]
you can try: "tl.utils.set_gpu_fraction(0.998) ".

**Comment by EdwardSmith1884** [comment]
Ah, thank you for the heads up, I'll correct it.
